# Generated by Django 5.2.17 on 2026-08-12 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='achievements/')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('institution', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('scope', models.CharField(choices=[('Intercollege', 'Intercollege'), ('Intracollege', 'Intracollege')], default='Intercollege', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=250)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('fee', models.PositiveIntegerField(default=0)),
                ('seats_total', models.PositiveIntegerField(default=0)),
                ('seats_left', models.PositiveIntegerField(default=0)),
                ('cover_image_url', models.URLField(blank=True, max_length=500)),
                ('cover_upload', models.ImageField(blank=True, null=True, upload_to='event_covers/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('extended', 'Extended'), ('pulled', 'Pulled')], default='active', max_length=20)),
                ('source_token', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('aim', models.TextField()),
                ('scope', models.CharField(choices=[('Intercollege', 'Intercollege'), ('Intracollege', 'Intracollege')], default='Intercollege', max_length=20)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=250)),
                ('budget', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('token', models.CharField(blank=True, max_length=100)),
                ('published', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_proposals', to=settings.AUTH_USER_MODEL)),
                ('published_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_proposal', to='events.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee_name', models.CharField(max_length=150)),
                ('attendee_id', models.CharField(max_length=50)),
                ('affiliation', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('fee_paid', models.PositiveIntegerField(default=0)),
                ('gst', models.PositiveIntegerField(default=0)),
                ('total_paid', models.PositiveIntegerField(default=0)),
                ('transaction_hash', models.CharField(max_length=100, unique=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='events.event')),
            ],
            options={
                'unique_together': {('student', 'event')},
            },
        ),
    ]
