# Generated by Django 5.2.17 on 2026-08-15 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_college_instituteprofile_college_and_more'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='accounts.college'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='target_college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='accounts.college'),
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_type',
            field=models.CharField(choices=[('INTRA_COLLEGE', 'Intra-College'), ('INTER_COLLEGE', 'Inter-College')], default='INTER_COLLEGE', max_length=20),
        ),
    ]
